version: "3"
services:
  mysqldb:
    image: mysql:8
    restart: always
    networks:
      - bora-app-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=db_bora  
  app-spring-boot:
    image: iddockerjms/bora-app:latest
    ports:
      - "8080:8080"
    networks:
      - bora-app-mysql
    restart: on-failure
    depends_on:
      - mysqldb
networks:
  bora-app-mysql: